### ISSUE TITLE
audio files??

### ISSUE THREAD

**Issue by Squire298** [srebosura/TalkingHAMRepeaterController#1]
would you happen to have the audio files for people to download, if they want to build this maybe it will be good to have this run out of the box?

**Comment by srebosura** [comment]
[dfplayer_files.zip](https://github.com/srebosura/TalkingHAMRepeaterController/files/10388872/dfplayer_files.zip)

I have attached the sample mp3 files. The filenames of the mp3 files needs to be in the correct order as it is use in the Arduino sketch or code. I recommend to use FAT sorter when writing the files to the SD card for DF player module. You have to compress the mp3 files to lower bit rate to be able to use the internal memory of the JQ6500 mp3 module.
