### ISSUE TITLE
schematic??

### ISSUE THREAD

**Issue by Squire298** [srebosura/TalkingHAMRepeaterController#2]
Are you able to supply a schematic?

**Comment by srebosura** [comment]
![final_layout](https://user-images.githubusercontent.com/24371616/211766975-39362731-2dce-44fe-8083-7457cacfdff3.jpeg)
![talking_repeater_COR_realtimeclock_DFplayer](https://user-images.githubusercontent.com/24371616/211767020-65d0c73c-d3d5-4700-927f-466911e3d77d.jpg)
