### ISSUE TITLE
Silk screen issue

### ISSUE THREAD

**Issue by Squire298** [srebosura/TalkingHAMRepeaterController#4]
in fault finding why this unit doesn't work is because the transistors are wrong way round, C and E need to be reversed.

**Comment by Squire298** [comment]
and you have 2N5164 isn't it meant to be a 2N5461? this is for the audio output

**Comment by srebosura** [comment]
Sorry for very late response. Yes, it's a typo 2N5461 thru 2n5464 will do. It's an N channel JFET for muting the station ID during air traffic. You can also bypass that feature. Thanks

**Comment by Squire298** [comment]
you still have this typo in your latest release..........
