### ISSUE TITLE
unable to trigger more than one time

### ISSUE THREAD

**Issue by Squire298** [srebosura/TalkingHAMRepeaterController#5]
After keying the rx, it doesn't seem to allow you to retrigger it again unless i restart it.

**Comment by srebosura** [comment]
Sorry for the very delayed response. Did it happen on the first boot and the first loading the sketch? Likely the eeprom data read by the variables were null. I think I did make fixes to this kind of situation when using a brandnew Arduino. Restarting or reset should help but you can execute the dtmf code reset to default command #1179 from on my original sketch.
