### ISSUE TITLE
Small Schematic Error

### ISSUE THREAD

**Issue by k7ilo** [srebosura/TalkingHAMRepeaterController#6]
Hello

I noticed that the Speaker and Ground identifications on the mp3 player are backwards.  Its showing the Speaker out connected to ground and Ground is connected to the Audio out combining.

I just thought I would let you know so that it would not confuse someone who would not catch it.

Thanks and GREAT project.

K7ILO

**Comment by srebosura** [comment]
It's an obvious mistake on the schematic. Thanks
